run_unit_test:
  stage: test
  image: gradle:8.1.1
  script:
    - gradle test
  artifacts:
    reports:
      junit:
        - build/test-results/test/*.xml
      coverage:
        - build/reports/jacoco/test/html
